### ISSUE TITLE
www redirection

### ISSUE THREAD

**Issue by yechoi42** [humansof42seoul/Humansof42#1]
www.humansof42.com 안되는 문제

**Comment by jwon42** [comment]
https://xetown.com/tips/1172256

**Comment by yechoi42** [comment]
서버블록에서 아무리 조정을 해줘도 www 도메인 리다이렉션이 안됐다. 알고보니 gcp domain 등록 문제였던 것. www 도메인을 따로 gcp DNS에 등록해줘야 함


> 선택사항: 도메인 이름의 프리픽스로 CNAME 레코드를 추가합니다(예: www.).
> 
> 레코드 집합 추가를 클릭합니다.
> DNS 이름 필드에 도메인의 프리픽스 www를 추가합니다.
> 리소스 레코드 유형에서 CNAME을 선택합니다.
> 표준 이름에 도메인 이름과 마침표를 입력합니다(예: example.com.).
> 만들기를 클릭합니다.

https://cloud.google.com/dns/docs/tutorials/create-domain-tutorial
